<a href="https://colab.research.google.com/github/JakeOh/20230228_itwill_java140_lab_python/blob/main/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# `np.ndarray` 클래스의 속성(property)

In [2]:
arr = np.ones(shape=(2, 3)) # 모든 원소가 1.0인 (2, 3) 모양의 배열

In [3]:
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
arr.dtype  # 배열 원소의 데이터 타입

dtype('float64')

In [5]:
arr.shape  # 배열의 모양: 배열의 각 축(axis)를 따라서 있는 원소의 개수.

(2, 3)

In [6]:
arr.ndim  # 배열의 차원(dimension): 배열의 축(axis)이 개수.

2

In [7]:
arr.size  # 배열의 크기: 배열의 전체 원소 개수

6

In [8]:
arr = np.arange(10)  # [0, 10) 범위의 1씩 증가하는 정수들로 만들어진 1차원 배열
print(arr)
print('dtype:', arr.dtype)
print('shape:', arr.shape)
print('ndim:', arr.ndim)
print('size:', arr.size)

[0 1 2 3 4 5 6 7 8 9]
dtype: int64
shape: (10,)
ndim: 1
size: 10


# indexing

*  Python list:
    *  `list[i], list[i][j], list[i][j][k], ...`
*  numpy ndarray:
    *  `array[i], array[i][j], array[i][j][k], ...`
    *  `array[i], array[i, j], array[i, j, k], ...`


In [9]:
arr = np.arange(1, 13).reshape((3, 4))
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
arr[0]

array([1, 2, 3, 4])

In [11]:
arr[0, 1]  # arr[0][1]과 동일.

2

# slicing

## 1차원 배열 slicing

In [12]:
np.random.seed(1)
arr = np.random.randint(100, size=10)  # [0, 100) 범위의 정수 난수 10개를 갖는 1차원 배열
print(arr)

[37 12 72  9 75  5 79 64 16  1]


In [13]:
arr[2:6]

array([72,  9, 75,  5])

In [14]:
arr[:3]  # arr[0:3]과 동일

array([37, 12, 72])

In [19]:
arr[-3:]

array([64, 16,  1])

In [17]:
arr[7:]  # arr[7:10]과 동일.

array([64, 16,  1])

## 2차원 배열 slicing

In [20]:
np.random.seed(10)
arr = np.random.randint(100, size=(4, 5))
print(arr)

[[ 9 15 64 28 89]
 [93 29  8 73  0]
 [40 36 16 11 54]
 [88 62 33 72 78]]


In [21]:
# 첫 2개의 row를 선택. 컬럼의 모든 원소 선택.
arr[:2, :]

array([[ 9, 15, 64, 28, 89],
       [93, 29,  8, 73,  0]])

In [25]:
arr[:2]

array([[ 9, 15, 64, 28, 89],
       [93, 29,  8, 73,  0]])

In [26]:
# 첫 2개의 row에서 첫 3개의 column 원소들
arr[:2, :3]

array([[ 9, 15, 64],
       [93, 29,  8]])

In [27]:
arr[2:, 3:]

array([[11, 54],
       [72, 78]])

# Shape 변경

## `np.ndarray.reshape(shape)`

배열의 모양을 변경한 새로운 배열을 리턴.

In [28]:
arr_1d = np.arange(12)
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [29]:
arr_2d = arr_1d.reshape((3, 4))
print(arr_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
print(arr_1d)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [31]:
# reshape을 할 때 자동으로 계산될 수 있는 차원의 값은 -1로 설정할 수 있음.
arr_2d = arr_1d.reshape((2, -1))  # (2, 6)
print(arr_2d)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]


In [32]:
arr_2d = arr_1d.reshape((-1, 3))  # (4, 3)
print(arr_2d)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


## `np.ndarray.ravel()`

1차원으로 변환된 배열의 **view**를 리턴. 새로운 배열이 리턴되는 것이 아님. 단지 모양만 다르게 보여줌.

In [33]:
print(arr_2d)  # (4, 3) shape의 2차원 배열

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [34]:
raveled = arr_2d.ravel()
print(raveled)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [36]:
raveled[0] = 100  # 모양이 변경된 1차원 배열의 원소 값을 변경
print(raveled)

[100   1   2   3   4   5   6   7   8   9  10  11]


In [37]:
print(arr_2d)  # ravel() 결과 배열에서 값을 변경하면 원본 2차원 배열의 원소도 변경

[[100   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]


## `np.ndarray.flatten()`

1차원으로 변환된 배열의 **복사본**을 리턴. 원본 배열과는 별개의 *새로운 배열*을 리턴.

In [38]:
print(arr_2d)

[[100   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]


In [39]:
flattened = arr_2d.flatten()
print(flattened)

[100   1   2   3   4   5   6   7   8   9  10  11]


In [41]:
flattened[0] = 0
print(flattened)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [42]:
print(arr_2d)  # flatten() 결과에서 값을 변경한 것은 원본 2차원 배열에 아무 영향을 주지 않음.

[[100   1   2]
 [  3   4   5]
 [  6   7   8]
 [  9  10  11]]


## `np.newaxis` 속성을 사용한 차원 늘리기

In [43]:
arr = np.arange(5)  # [0, 5) 범위의 정수 5개를 갖는 (5,) shape의 1차원 배열
print(arr)
print(arr.shape)
print(arr.ndim)

[0 1 2 3 4]
(5,)
1


In [44]:
# 배열 arr을 (1, 5) shape의 2차원 배열로 변환
arr_2d = arr.reshape((1, -1))  # (1, 5)
print(arr_2d)

[[0 1 2 3 4]]


In [46]:
result = arr[np.newaxis, :]
print(result)

[[0 1 2 3 4]]


In [47]:
# 배열 arr을 (5, 1) shape의 2차원 배열로 변환
arr_2d = arr.reshape((-1, 1))  # (5, 1), (5, -1)
print(arr_2d)

[[0]
 [1]
 [2]
 [3]
 [4]]


In [48]:
result = arr[:, np.newaxis]
print(result)

[[0]
 [1]
 [2]
 [3]
 [4]]


# 배열 합치기(concatenate)

## `np.concatenate([array1, array2, ...], axis=0)`

특정 축(axis) 방향으로 이어 붙이기.

In [49]:
arr1 = np.arange(6).reshape((2, 3))
print(arr1)

[[0 1 2]
 [3 4 5]]


In [50]:
arr2 = np.array([[10, 20, 30]])  # (1, 3)
print(arr2)

[[10 20 30]]


In [51]:
result = np.concatenate([arr1, arr2])  # axis 기본값 0.
print(result)

[[ 0  1  2]
 [ 3  4  5]
 [10 20 30]]


In [52]:
arr3 = np.array([[100], [200]])  # (1, 2) shape의 2차원 배열
print(arr3)

[[100]
 [200]]


In [53]:
result = np.concatenate([arr1, arr3], axis=1)
print(result)

[[  0   1   2 100]
 [  3   4   5 200]]


## `np.r_[array1, array2]`, `np.c_[array1, array2]`

*  `np.r_`: 행(row) 이어붙이기. concatenate(axis=0)
*  `np.c_`: 열(column) 이어붙이기. concatenate(axis=1)


In [54]:
np.r_[arr1, arr2]

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 20, 30]])

In [55]:
np.c_[arr1, arr3]

array([[  0,   1,   2, 100],
       [  3,   4,   5, 200]])