<a href="https://colab.research.google.com/github/JakeOh/20230228_itwill_java140_lab_python/blob/main/ml01_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# `np.ndarray` 클래스의 속성(property)

In [2]:
arr = np.ones(shape=(2, 3)) # 모든 원소가 1.0인 (2, 3) 모양의 배열

In [3]:
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [4]:
arr.dtype  # 배열 원소의 데이터 타입

dtype('float64')

In [5]:
arr.shape  # 배열의 모양: 배열의 각 축(axis)를 따라서 있는 원소의 개수.

(2, 3)

In [6]:
arr.ndim  # 배열의 차원(dimension): 배열의 축(axis)이 개수.

2

In [7]:
arr.size  # 배열의 크기: 배열의 전체 원소 개수

6

In [8]:
arr = np.arange(10)  # [0, 10) 범위의 1씩 증가하는 정수들로 만들어진 1차원 배열
print(arr)
print('dtype:', arr.dtype)
print('shape:', arr.shape)
print('ndim:', arr.ndim)
print('size:', arr.size)

[0 1 2 3 4 5 6 7 8 9]
dtype: int64
shape: (10,)
ndim: 1
size: 10


# indexing

*  Python list:
    *  `list[i], list[i][j], list[i][j][k], ...`
*  numpy ndarray:
    *  `array[i], array[i][j], array[i][j][k], ...`
    *  `array[i], array[i, j], array[i, j, k], ...`


In [9]:
arr = np.arange(1, 13).reshape((3, 4))
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
arr[0]

array([1, 2, 3, 4])

In [11]:
arr[0, 1]  # arr[0][1]과 동일.

2

# slicing

## 1차원 배열 slicing

In [12]:
np.random.seed(1)
arr = np.random.randint(100, size=10)  # [0, 100) 범위의 정수 난수 10개를 갖는 1차원 배열
print(arr)

[37 12 72  9 75  5 79 64 16  1]


In [13]:
arr[2:6]

array([72,  9, 75,  5])

In [14]:
arr[:3]  # arr[0:3]과 동일

array([37, 12, 72])

In [19]:
arr[-3:]

array([64, 16,  1])

In [17]:
arr[7:]  # arr[7:10]과 동일.

array([64, 16,  1])

## 2차원 배열 slicing

In [20]:
np.random.seed(10)
arr = np.random.randint(100, size=(4, 5))
print(arr)

[[ 9 15 64 28 89]
 [93 29  8 73  0]
 [40 36 16 11 54]
 [88 62 33 72 78]]


In [21]:
# 첫 2개의 row를 선택. 컬럼의 모든 원소 선택.
arr[:2, :]

array([[ 9, 15, 64, 28, 89],
       [93, 29,  8, 73,  0]])

In [25]:
arr[:2]

array([[ 9, 15, 64, 28, 89],
       [93, 29,  8, 73,  0]])

In [26]:
# 첫 2개의 row에서 첫 3개의 column 원소들
arr[:2, :3]

array([[ 9, 15, 64],
       [93, 29,  8]])

In [27]:
arr[2:, 3:]

array([[11, 54],
       [72, 78]])

# Shape 변경