<a href="https://colab.research.google.com/github/JakeOh/20230228_itwill_java140_lab_python/blob/main/py13_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 데이터 분석 패키지

Google Colab에는 데이터 분석과 머신 러닝에 필요한 대부분의 패키지들이 이미 설치가 되어 있음.

*  NumPy: 다차원 배열(n-dimensional array)을 다루는 패키지. 머신 러닝에서 중요하게 사용됨.
*  pandas: 시리즈(Series), 데이터프레임(DataFrame)을 다루는 패키지. 데이터 분석에서 기본으로 사용되는 패키지.
*  matplotlib: 데이터 시각화(그래프).
*  seaborn: 데이터 시각화. 통계 작업.


In [1]:
import numpy as np
import pandas as pd
import matplotlib as mpl
import seaborn as sns

In [2]:
print('NumPy version:', np.__version__)
print('pandas version:', pd.__version__)
print('Matplotlib version:', mpl.__version__)
print('seaborn version:', sns.__version__)

NumPy version: 1.22.4
pandas version: 1.5.3
Matplotlib version: 3.7.1
seaborn version: 0.12.2


# Python `list` class

*  여러 개의 값들을 저장할 수 있는 데이터 타입.
*  인덱스를 기반으로 값들을 저장, 참조하는 데이터 타입.
    *  indexing: 인덱스를 사용해서 원하는 위치의 값을 참조, 변경.
    *  slicing: `[start, end)` 인덱스 범위의 값들로 이루어진 부분집합을 잘라내는 방법.
*  `list + list`: 2개의 리스트를 이어붙이기(concatenate).
*  `list * int`, `int * list`: 리스트의 원소들을 정수만큼 반복해서 복제(replicate).

In [3]:
list1 = [1, 2, 3, 4]
list2 = [10, 20, 30, 40]

In [4]:
# indexing:
print(list1[0])  # list1의 첫번째 원소
print(list1[3], list1[-1])  # list1의 마지막 원소

1
4 4


In [5]:
# slicing
print(list1[:3])  # list1에서 앞에서 3개 원소 자르기
print(list1[-3:])  # list1에서 뒤에서 3개 원소 자르기

[1, 2, 3]
[2, 3, 4]


In [6]:
list1 + list2

[1, 2, 3, 4, 10, 20, 30, 40]

In [7]:
list1 * 3

[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]

In [8]:
# list1, list2에서 같은 인덱스 위치의 원소들끼리 덧셈
[x + y for x, y in zip(list1, list2)]

[11, 22, 33, 44]

In [9]:
# list1의 모든 원소에 3을 곱함.
[3 * x for x in list1]

[3, 6, 9, 12]

# NumPy

*  배열(ndarray)을 쉽고 빠르게 연산(+, -, *, /, //, %)을 수행하는 라이브러리.
*  NumPy 패키지의 함수 또는 메서드들을 대부분 반복문의 기능을 가지고 있음.
*  np.ndarray 클래스: NumPy 패키지에서 기본 타입 클래스. n차원 배열(n-dimensional array).
    *  `ndarray`는 같은 인덱스(위치)에 있는 원소들끼리 연산을 수행.

In [10]:
array1 = np.array([1, 2, 3])  # python의 list 객체를 numpy의 ndarray 객체로 변환.

In [11]:
type(array1)

numpy.ndarray

In [12]:
print(array1)  # print() 함수는 __str__ 메서드의 리턴값을 출력

[1 2 3]


In [13]:
array1  # expression은 __repr__ 메서드의 리턴값을 출력

array([1, 2, 3])

In [14]:
array2 = np.array([4, 5, 6])
print(array2)

[4 5 6]


In [15]:
# ndarray의 사칙연산 - 같은 인덱스의 원소들끼리(element-wise) 연산 수행
print(array1 + array2)
print(array1 - array2)
print(array1 * array2)
print(array1 / array2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


## `ndarray` 클래스의 속성들

In [16]:
print(array1)
print('ndim:', array1.ndim)  # 차원(dimesion). 배열의 축(axis)의 개수.
print('size:', array1.size)  # 배열의 크기. 원소 개수.
print('shape:', array1.shape)  # 배열의 모양. 각 차원에서의 원소 개수.
print('dtype:', array1.dtype)  # 배열 원소의 데이터 타입.

[1 2 3]
ndim: 1
size: 3
shape: (3,)
dtype: int64


`ndarray`는 한 가지 타입의 데이터들만 저장할 수 있는 데이터 타입 - `list`와 다른 점.

## 2차원 배열

In [17]:
array_2d = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

In [18]:
type(array_2d)

numpy.ndarray

In [19]:
print(array_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [20]:
array_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
print('ndim:', array_2d.ndim)  # 차원
print('size:', array_2d.size)  # 크기
print('shape:', array_2d.shape)  # 모양
print('dtype:', array_2d.dtype)  # 데이터 타입

ndim: 2
size: 12
shape: (3, 4)
dtype: int64


### 2차원 `ndarray`의 인덱스 사용 방법:

*  `array[i][j]` - Python list와 같은 사용 방법.
*  `array[i, j]` - ndarray에서만 사용 가능

In [22]:
array_2d[0, 0]  # array_2d[0][0]

1

In [23]:
array_2d[1, 2]

7

## `ndarray` 인덱스

In [24]:
# [0, 100) 범위의 정수 난수 10개를 갖는 ndarray 객체를 생성:
array = np.random.randint(0, 100, size=10)
print(array)

[94 86 90  0 80 70 92 48 56 81]


In [25]:
# indexing:
print(array[0])  # 첫번째 원소
print(array[-1])  # 마지막 원소

94
81


In [26]:
# slicing:
print(array[:3])  # 첫 3개 원소 자르기
print(array[-3:])  # 마지막 3개 원소 자르기

[94 86 90]
[48 56 81]


In [27]:
print(array[0])  # indexing -> 아이템(값)
print(array[0:1])  # slicing -> 배열(ndarray)

94
[94]


### fancy indexing

*  배열과 비슷한 객체(ndarray, list, tuple, set, ...)를 사용해서 원하는 원소들을 참조하는 방법.
*  fancy indexing의 결과는 ndarray.

In [28]:
print(array)
print(array[0])  # indexing
print(array[[0, 2, 4]])  # fancy indexing - 인덱스 0, 2, 4 원소들 찾기
print(array[[0]])  # fancy indexing -> 결과는 배열!

[94 86 90  0 80 70 92 48 56 81]
94
[94 90 80]
[94]


### boolean indexing

*  논리값(True/False)들의 배열(리스트, 튜플, ...)을 사용한 fancy indexing 방법.
*  배열에서 조건을 만족하는 원소들로 이루어진 부분집합(ndarray)를 만드는 방법.


In [29]:
print(array)
print(array[[True, False, True, False, True, False, True, False, True, False]])

[94 86 90  0 80 70 92 48 56 81]
[94 90 80 92 56]


In [30]:
# 배열 array의 원소들 중 홀수들만 찾기:
print(array % 2)
print(array % 2 == 1)
print(array[array % 2 == 1])

[0 0 0 0 0 0 0 0 0 1]
[False False False False False False False False False  True]
[81]


In [31]:
# 배열 array의 원소들 중에서 50 이상인 숫자들의 배열을 찾기:
print(array[array >= 50])

[94 86 90 80 70 92 56 81]


## NumPy의 통계 함수, 메서드

*  np.function(ndarray) 함수
*  np.ndarray.method() 메서드


In [32]:
array = np.array([1, 2, 3, 4, 5])
print(array)

[1 2 3 4 5]


In [33]:
# 합계:
print(np.sum(array))  # 함수
print(array.sum())  # 메서드

15
15


In [34]:
# 평균
print(np.mean(array))  # 함수
print(array.mean())  # 메서드

3.0
3.0


*  numpy 패키지를 사용
*  [0, 100) 범위의 정수 난수 10개를 갖는 ndarray를 생성.
*  배열의 원소들의 최댓값, 최솟값, 평균(mean), 분산(variance), 표준편차(standard deviation)를 출력.
*  배열의 원소들 중 평균보다 큰 값들로 이루어진 배열을 만들고 출력.

In [40]:
np.random.seed(1)  # 난수들을 생성하는 seed를 설정. -> 항상 같은 숫자들을 생성.
array = np.random.randint(0, 100, size=10)
print(array)

[37 12 72  9 75  5 79 64 16  1]


In [42]:
print('최댓값:', np.max(array), array.max())
print('최솟값:', np.min(array), array.min())
print('평균:', np.mean(array), array.mean())
print('분산:', np.var(array), array.var())
print('표준편차:', np.std(array), array.std())

최댓값: 79 79
최솟값: 1 1
평균: 37.0 37.0
분산: 933.2 933.2
표준편차: 30.548322376196047 30.548322376196047


In [43]:
array[array > np.mean(array)]

array([72, 75, 79, 64])

## 2차원 배열에서의 통계 함수, 메서드

In [44]:
# [0, 100) 범위의 정수 난수를 갖는 (3, 4) 모양(shape)을 갖는 2차원 ndarray:
np.random.seed(1)
array = np.random.randint(100, size=(3, 4))
print(array)

[[37 12 72  9]
 [75  5 79 64]
 [16  1 76 71]]


In [45]:
np.sum(array)  # axis=None(기본값): 배열의 모든 원소들의 합계

517

In [46]:
np.sum(array, axis=0)  # axis=0: 2차원 배열에서 첫번째 인덱스가 증가하는 축 방향으로 계산.

array([128,  18, 227, 144])

In [47]:
np.sum(array, axis=1)  # axis=1: 2차원 배열에서 두번째 인덱스가 증가하는 축 방향으로 계산.

array([130, 223, 164])

In [48]:
np.sum(array, axis=1, keepdims=True)

array([[130],
       [223],
       [164]])